### PR TITLE
feat: support attributes in MenuItemStack

### PR DESCRIPTION
**Pull request by EnzoShoes**
Add support for custom attributes #20

### CODE REVIEW

**Comment by Maxlego08** [comment]
Will it work without any problems in the 1.8 to 1.20 versions ?

**Comment by lijinhong11** [comment]
It just only for1.13.2+. In lower versions, that may need NBTAPI (the best solution)

> Will it work without any problems in the 1.8 to 1.20 versions ?

**Comment by Maxlego08** [comment]
The problem is that I am afraid that in the versions below that, the plugin will trigger an error and not run the plugin since the classes do not exist

**Comment by lijinhong11** [comment]
> The problem is that I am afraid that in the versions below that, the plugin will trigger an error and not run the plugin since the classes do not exist

So just add a support to add nbt tags

**Comment by EnzoShoes** [comment]
Is this ok ?

**Pull request merged**
