### PR TITLE
Open menu with item

### PR DESCRIPTION
**Pull request by EnzoShoes**
Add possibility to open menu with item #28.

### CODE REVIEW

**Comment by 1464005696** [comment]
Thanks for update it!

**Comment by lijinhong11** [comment]
this is pretty cool

**Comment by Maxlego08** [comment]
Thank you for your PR, I have two changes:
1. In your class OpenWithItem dont use an ItemStack but instead use a MenuItemStack
2. You should create a verification enum, if use whant to check only the material, name, lore, model id or use the method isSimilar from ItemStack

If you have time to do it would be great, otherwise I could make myself

**Comment by EnzoShoes** [comment]
Can I try to finish using what you made or are you working on it ?

**Comment by Maxlego08** [comment]
you can continue

**Comment by EnzoShoes** [comment]
Is this what you had in mind for the enum ?

**Comment by Maxlego08** [comment]
I’ll take care of the rest, thank you !

**Comment by Maxlego08** [comment]
Here is the final rendering of the configuration
```yml
# Open this menu by clicking a specific item
#
openWithItem:
  # Define the item that will be clicked
  item:
    material: clock
  # Look at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/Action.html
  actions:
    - LEFT_CLICK_BLOCK
    - LEFT_CLICK_AIR
  # Définissez ensuite le type de vérification.
  # Depending on your configuration and need you will define a certain type of verification. Here are all the types that exist:
  # - full -> Allows to check the itemStack in full, will use the ItemStack#isSimilar method.
  # - material -> Allows to check only the material
  # - name -> Allows to check only the display name
  # - lore -> Allows to check only the lore
  # - modelid -> Allows to check only the Custom Model Id
  type: material
```

**Pull request merged**
